### PR TITLE
Delayed exit fix

### LINKED ISSUE #9: Application take time to close

### PR DESCRIPTION
**Pull request by MrCraftCod**
Resolve #9

### CODE REVIEW

File: src/main/java/fr/mrcraftcod/m3u8recorder/download/DownloadManager.java [hunk 1]
```diff
@@ -55,13 +55,12 @@ public static LiveStream downloadFromProvider(ProviderInfos infos)
...
+	 * Close this manager.
 	 */
-	public static void stopAll()
+	public static void close()
 	{
-		Log.info("Stopping everything");
-		STREAM_DOWNLOADERS.forEach(LiveStreamDownloader::stop);
-		CHUNK_DOWNLOADERS.forEach(LiveStreamChunkDownloader::stop);
+		stopAll();
+		executor.shutdown();
```
Comment (MrCraftCod) [inline src/main/java/fr/mrcraftcod/m3u8recorder/download/DownloadManager.java]: The executor is shutdown but something else is preventing the program to close.
